version: '3.4'
services:
  db:
    image: postgres:lastet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rteCRUD
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    ports:
        - "8000:80"
    depends_on:
        - db
    environment:
        ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=rteCRUD;Username=postgres;Password=1234"
volumes:
  pgdata:
